### ISSUE TITLE
USER STORY: Create admin site

### ISSUE THREAD

**Issue by AdrianaStoi** [AdrianaStoi/Licensing-Capsule#1]
### USER STORY: 
As an **admin**, I can **access an admin panel where I can view users, comments, and posts and filter in the sections** so that **I can efficiently oversee and maintain the website and its content.**

### Acceptance Criteria
* As an admin, I can login to an admin account and access a secure admin panel.
* From the admin panel, I should be able to easily access, view and manage the users, comments and posts.                                                                                                                           
* Each section (Users, Comments, Categories, Articles) should provide filter options relevant to that section.

### Tasks
- [x] Set up the Django admin interface by configuring it in the project's settings.
- [x] Run the createsuperuser management command to create an initial superuser account with administrative privileges.
- [x] Create class PostAdmin, AdminComment, ProductFamily in admin.py.
- [x] Add filter and search to each class to add filters and search to corresponding sections on the Admin Panel.
