### ISSUE TITLE
USER STORY: View most liked and commented articles

### ISSUE THREAD

**Issue by AdrianaStoi** [AdrianaStoi/Licensing-Capsule#10]
### USER STORY: 
As a **site user,** I can **view the most liked and commented articles** so that **I can stay informed about licensing trends and most discussed topics within the community.**

### Acceptance Criteria 
* On the site's homepage, the user should be able to see a section of the articles that are sorted by the number of likes and comments. 
* Each article in this section should display the number of likes and comments it has received, allowing the user to quickly identify popular and engaging articles.
* When clicking on an article title from the list, it should direct the user to the full article, allowing them to read the content and explore the discussions in the comments section.

### Tasks
- [x] Design the layout for the section displaying the most liked and commented articles and add a relevant image, ensuring it is visually appealing and user-friendly. 
- [x] Sort articles based on the number of likes and comments and display 2 of the most liked and/or commented.
- [x] Implement navigation links that allow users to easily access the full content of an article when they click on its title in the list of most liked and commented articles.
