### ISSUE TITLE
USER STORY: Account Registration

### ISSUE THREAD

**Issue by AdrianaStoi** [AdrianaStoi/Licensing-Capsule#14]
### USER STORY: 
As a **frequent site user,** I can **register on the site** so that **I can provide feedback on the content and to the content creator and engage with other readers.**

### Acceptance Criteria 
* There should be a clearly visible and accessible "Register" option on the site's interface.
* When the user clicks on "Register", they should be directed to a registration page that includes fields for entering username, email address and password.
* After successfully registering, the user should be prompted with a message on the page that they have registered successfully. 

### Tasks
- [x] Add the Register option at the top right corner of the page on the navigation bar and style it accordingly.
- [x] Add allauth library for handling user authentication, registration. 
- [x]  When the account is created a message should appear on the page to notify the user of their successful registration.
