### ISSUE TITLE
USER STORY: Create user profile page

### ISSUE THREAD

**Issue by AdrianaStoi** [AdrianaStoi/Licensing-Capsule#16]
### USER STORY: 
As a **registered user** I can **access my user profile page** so that **I can manage my comments and see their status (approved or pending).**

### Acceptance Criteria 
* When the user logs in and accesses their user profile page, they should see a section that displays a list of all the comments they have made on the site.
* Each comment in the list should include information such as the article title, date and time of the comment, the status of the comment (e.g., approved or pending).

### Tasks
- [ ] Create a User Profile account page using HTML and style it with CSS. 
- [ ] To display the list of comments use loops to iterate through the user's comments and display them in a list.
- [ ] Display the user’s comments on the user profile with the necessary information to include information such as the article title, date and time of the comment, the status of the comment (approved or pending).

**Comment by AdrianaStoi** [comment]
Future feature
