### ISSUE TITLE
USER STORY: Edit and delete comments

### ISSUE THREAD

**Issue by AdrianaStoi** [AdrianaStoi/Licensing-Capsule#17]
### USER STORY:
As a **registered user,** I can **edit and delete comments** so that **I can manage my contributions, edit, and remove mistakes or inaccurate information.**

###  Acceptance Criteria 
* Each comment should include information date and time of the comment, and options for the user to manage the comment (e.g., edit or delete).

###  Tasks
- [x] For comment edit and delete, editcomment.html page and deletecomment.html page. 
- [x] Create edit comment and delete comment functions in views.py
- [x] Add the url paths to urls.py and add the links to the html templates.
- [x] Add the edit and delete urls to the Edit and Delete options.
