### ISSUE TITLE
USER STORY: Like an article

### ISSUE THREAD

**Issue by AdrianaStoi** [AdrianaStoi/Licensing-Capsule#19]
### USER STORY:
As a **registered site User,** I can **like an article** so that **I can show appreciation and support to the content creator.**

###  Acceptance Criteria 
* When the user is logged in as a registered user and views an article, the user should be able to click on the like button which should increment the number of like counts on the article. 

### Tasks
- [x] Add an icon for “like” on each article. 
- [x] Add an if condition to the article.html page and if the user is authenticated, when they click on like icon, the number of likes should be increased. 
- [x] The user should also have the option to unlike the article.
