### ISSUE TITLE
USER STORY: View likes and comments

### ISSUE THREAD

**Issue by AdrianaStoi** [AdrianaStoi/Licensing-Capsule#20]
### USER STORY:
As a **site user** I can **view number of likes and comments of an article** so that **I can gain valuable insights and perspectives from other readers regarding the topic.**

### Acceptance Criteria 
* The user should be able to view the number of likes and comments for each article displayed on the blog.
* The likes and comments counts should be updated accordingly when feedback is provided by a registered user. 
* The likes and comments counts should be displayed alongside each article's title or within a clearly visible area.
* If not registered the user should not be able to like an article. He should receive a message indicating that he must log in in order to like the article. 

### Tasks
- [x] Add icon for like and the number of likes alongside the article’s date of post. 
- [x] Create the Comments section area at the bottom of the blog post which displays all users’ approved comments.
- [x] Create an alert so that when an unregistered user clicks on the like button, he is informed that he must login or register.
