### ISSUE TITLE
USER STORY: Article structure

### ISSUE THREAD

**Issue by AdrianaStoi** [AdrianaStoi/Licensing-Capsule#4]
### USER STORY: 
As an **admin,** I can **add a title, slug, author, image, content, select status of an article** so that **I can efficiently create the articles for the website.**

### Acceptance Criteria 
* When creating or updating an article, the admin should be able to input a clear and descriptive title for the article and generate an automatic slug. 
* There should be an option to select the author of the article from a list of authors or user accounts. 
* The admin should be able to upload an image for the article from their image repository or local device. 
* There should be a content field where the admin can write and format the article. 
* In case of validation errors or missing information, the system should provide informative error messages to guide the admin in making corrections.

### Tasks
- [x] Create Article class model passing the necessary fields including their titles, status, slug, creation date and update date.
- [x]  In admin.py, import Article model 
- [x] Install and setup Summernote library for the Content post. 
- [x] Create class in admin.py and add necessary fields to be displayed 
- [x] In the ArticleAdmin class add list_display and pass the values ('title', 'slug', 'status', 'created_on')
- [x] Add  prepopulated_fields  and set to a dictionary mapping field names to the fields it should prepopulate from, in this case {"slug": ("title",)}
