### ISSUE TITLE
USER STORY: User administration

### ISSUE THREAD

**Issue by AdrianaStoi** [AdrianaStoi/Licensing-Capsule#6]
### USER STORY: 
As an **admin,** I can **view and manage registered users** so that **I can monitor the user base**

### Acceptance Criteria 
* The admin should be able to access a user management dashboard or section from the admin panel.
* The user list should display the usernames, email addresses, and Staff status of all authenticated users.
* Admin should be able to search and filter the user list based on various criteria (e.g., username, email address).                                                                                                                 * Define and customize permissions for each role, specifying which features or areas of the site they can access. Changes in permissions or roles should take effect immediately for the affected users.

### Tasks
- [x] Set up the Django admin interface by configuring it in the project's settings.
- [x] Run the createsuperuser management command to create an initial superuser account with administrative privileges.
- [x] This creates basic admin account which displays users and access to user management.
