### ISSUE TITLE
USER STORY: View article details

### ISSUE THREAD

**Issue by AdrianaStoi** [AdrianaStoi/Licensing-Capsule#8]
### USER STORY:
As a **site user,** I can **view the article’s author and publication date and time** so that **I stay informed about contributors and remain up to date with the latest developments in specific licensing news and updates.**

### Acceptance Criteria 
* When the user accesses an article, he should clearly see the name of the article's author prominently displayed at the beginning of the article content.
* The publication date and time of the article should be visibly provided next to the author's name to indicate when the article was published.

### Tasks
- [x] Design the layout and user interface for the article page, ensuring it blends with the site's design.
- [x] Write HTML and CSS code to structure and style the article page. 
- [x] Add the author’s name, and published date and time field to the article so they are visible to the users.
